// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4

package jwt

import (
	"testing"

	"github.com/spf13/cobra"
)

func TestInit_9ce19e7e35(t *testing.T) {
	tokenCmd.PersistentFlags().StringVar(&jwtFlagPrivateKey, "key", "", "private key")
	tokenCmd.PersistentFlags().StringVar(&jwtFlagFields, "fields", "", "JWT fields in JSON format")

	keyFlag := tokenCmd.Flag("key")
	if keyFlag == nil {
		t.Error("Expected key flag to be set")
	}

	if keyFlag.DefValue != "" {
		t.Errorf("Expected default value of key flag to be empty, but got %s", keyFlag.DefValue)
	}

	fieldsFlag := tokenCmd.Flag("fields")
	if fieldsFlag == nil {
		t.Error("Expected fields flag to be set")
	}

	if fieldsFlag.DefValue != "" {
		t.Errorf("Expected default value of fields flag to be empty, but got %s", fieldsFlag.DefValue)
	}
}
