// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4

package daemon

import (
	"flag"
	"testing"
	"time"
)

func TestInit_ac5bb3ce08(t *testing.T) {
	bindFlag := flag.Lookup("bind")
	if bindFlag == nil {
		t.Error("bind flag not found")
	} else {
		if bindFlag.DefValue != ":9096" {
			t.Errorf("expected default value of bind flag to be :9096, got %s", bindFlag.DefValue)
		}
	}

	gracefulDelayFlag := flag.Lookup("graceful.delay")
	if gracefulDelayFlag == nil {
		t.Error("graceful.delay flag not found")
	} else {
		if gracefulDelayFlag.DefValue != "50ms" {
			t.Errorf("expected default value of graceful.delay flag to be 50ms, got %s", gracefulDelayFlag.DefValue)
		}
	}
}
